<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>Play.Common</PackageId>
    <Version>1.0.2</Version>
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageTags>play, microservice, common, shared, library, MongoDb, RabbitMQ</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackRelease>true</PackRelease>
    <Title>Play.Common.Domain, desenvolvida por Bigai Software.</Title>
    <Authors>Marcos Cruz</Authors>
    <Company>Bigai Software, Santo André, SP, Brazil.</Company>
    <Description>Play.Common é uma biblioteca de código compartilhado nuget, escrita em dotnet core 8.0, que fornece suporte as operações de microserviços da aplicação Play.</Description>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/marcos-cruz/Play.Common.git</RepositoryUrl>
    <CurrentYear>$([System.DateTime]::Now.ToString(yyyy))</CurrentYear>
    <Copyright>Copyright ©2021-$(CurrentYear) Bigai Software, All rights reserved.</Copyright>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Update="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.7" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="MongoDb.Driver" Version="3.5.2" />
  </ItemGroup>

</Project>
